module.exports = [
    {
        "date": "25-05-2017",
        "hasFreeTerm": true,
        "hours":
        [
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ]
        ]
    },
    {
        "date": "26-05-2017",
        "hasFreeTerm": true,
        "hours":
        [
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ],
            [
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ],
                [
                    true,
                    false,
                    true
                ]
            ]
        ]
    }
]